In [1]:
import pandas as pd
df=pd.read_csv('bike_dataset.csv')
df.head()

,model_name,price,CC,mileage,type_of_bike,weight_in_kg,links,acceleration_speed,top_speed
0,Gravton Motors Quanta,99000,NaN,320.0,Electric Bike,100,https://www.carandbike.com/gravton-motors-bike...,4.2,70.0
1,Simple Energy One,109999,NaN,236.0,Electric Bike,110,https://www.carandbike.com/simple-energy-bikes...,3.6,100.0
2,Okaya Classiq,69900,NaN,200.0,Electric Bike,95,https://www.carandbike.com/okaya-bikes/classiq,NaN,25.0
3,Oben Electric Rorr,102999,NaN,200.0,Electric Bike,120,https://www.carandbike.com/oben-electric-bikes...,3.0,100.0
4,Ola Electric S1,85099,NaN,181.0,Electric Bike,121,https://www.carandbike.com/ola-electric-bikes/s1,2.9,116.0

In [3]:
df.describe

<bound method NDFrame.describe of                       model_name    price      CC  mileage   type_of_bike  \
0          Gravton Motors Quanta    99000     NaN    320.0  Electric Bike
1              Simple Energy One   109999     NaN    236.0  Electric Bike
2                  Okaya Classiq    69900     NaN    200.0  Electric Bike
3             Oben Electric Rorr   102999     NaN    200.0  Electric Bike
4                Ola Electric S1    85099     NaN    181.0  Electric Bike
..                           ...      ...     ...      ...            ...
356                 Aprilia RSV4  2369000  1099.0     12.0    Petrol Bike
357  Harley-Davidson Sportster S  1551000  1252.0     11.8    Petrol Bike
358              Suzuki Hayabusa  1640000  1340.0     11.0    Petrol Bike
359       Ducati Hypermotard 950  1402278   937.0      9.0    Petrol Bike
360  Harley-Davidson CVO Limited  4999000  1923.0      8.0    Petrol Bike

     weight_in_kg                                              links  \
0             100  https://www.carandbike.com/gravton-motors-bike...
1             110  https://www.carandbike.com/simple-energy-bikes...
2              95     https://www.carandbike.com/okaya-bikes/classiq
3             120  https://www.carandbike.com/oben-electric-bikes...
4             121   https://www.carandbike.com/ola-electric-bikes/s1
..            ...                                                ...
356           202      https://www.carandbike.com/aprilia-bikes/rsv4
357           228  https://www.carandbike.com/harley-davidson-bik...
358           266   https://www.carandbike.com/suzuki-bikes/hayabusa
359           176  https://www.carandbike.com/ducati-bikes/hyperm...
360           411  https://www.carandbike.com/harley-davidson-bik...

     acceleration_speed  top_speed
0                   4.2       70.0
1                   3.6      100.0
2                   NaN       25.0
3                   3.0      100.0
4                   2.9      116.0
..                  ...        ...
356                 NaN        NaN
357                 NaN        NaN
358                 NaN        NaN
359                 NaN        NaN
360                 NaN        NaN

[361 rows x 9 columns]>

In [5]:
# scaleing
from sklearn.preprocessing import MinMaxScaler
numeric_cols=['price','mileage','weight_in_kg','top_speed']
scaler=MinMaxScaler()
df[numeric_cols]=scaler.fit_transform(df[numeric_cols])
df[numeric_cols].head()

      price   mileage  weight_in_kg  top_speed
0  0.007671  1.000000      0.119048   0.257143
1  0.009054  0.730769      0.145503   0.428571
2  0.004012  0.615385      0.105820   0.000000
3  0.008174  0.615385      0.171958   0.428571
4  0.005923  0.554487      0.174603   0.520000

In [46]:
from sklearn.model_selection import train_test_split
x=df[['mileage','weight_in_kg']]
y=df[['price']]
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
print('X_train \n' ,X_train.head(),
      '\n x_test \n',X_test.head(),
      '\n y_train \n',y_train.head(),
      '\n y_test \n',y_test.head())

X_train
       mileage  weight_in_kg
150  0.094551      0.304233
281  0.032051      0.425926
280  0.032051      0.346561
238  0.041667      0.592593
176  0.074519      0.396825
 x_test
       mileage  weight_in_kg
186  0.070513      0.206349
255  0.038462      0.394180
45   0.230769      0.000000
26   0.307692      0.164021
216  0.051282      0.518519
 y_train
         price
150  0.016778
281  0.095196
280  0.073692
238  0.278169
176  0.019089
 y_test
         price
186  0.026534
255  0.135060
45   0.000252
26   0.001058
216  0.149271

In [48]:
# prediction
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred

array([[ 4.53477673e-02],
       [ 1.41176357e-01],
       [-6.70932651e-02],
       [ 1.05770565e-02],
       [ 2.02661978e-01],
       [ 7.87479260e-03],
       [ 1.35881023e-01],
       [ 6.95824056e-02],
       [ 1.74403256e-02],
       [-2.45609347e-02],
       [ 6.29632374e-02],
       [ 8.28207420e-02],
       [ 1.36949385e-01],
       [ 7.55398679e-03],
       [ 7.49160926e-02],
       [ 1.09357804e-01],
       [ 3.50892993e-01],
       [ 2.27592824e-01],
       [ 1.32977884e-01],
       [ 5.54258684e-02],
       [ 1.58177944e-02],
       [ 9.43426788e-02],
       [ 1.86737622e-01],
       [ 1.94496983e-01],
       [ 1.93540430e-01],
       [ 1.70300698e-01],
       [ 1.11198549e-02],
       [ 2.25718070e-01],
       [ 1.37518669e-01],
       [ 1.55738528e-01],
       [ 6.12337710e-02],
       [ 1.83539034e-01],
       [ 1.13844203e-01],
       [-4.94777950e-02],
       [ 5.49559247e-03],
       [ 7.02743253e-03],
       [-2.15703533e-02],
       [ 2.90363926e-01],
       [ 3.85129028e-01],
       [ 2.36492380e-01],
       [ 3.73664130e-02],
       [ 1.74403256e-02],
       [ 1.49524992e-01],
       [ 5.62371340e-02],
       [ 3.80869875e-02],
       [ 1.34385943e-02],
       [-2.67587526e-02],
       [ 1.93211502e-01],
       [ 1.87326895e-01],
       [-2.10194328e-02],
       [ 1.06978675e-01],
       [ 1.14104304e-02],
       [-8.18672917e-03],
       [ 2.25167150e-01],
       [-6.11007670e-04],
       [-1.45455523e-02],
       [ 2.53147446e-02],
       [ 1.79290448e-01],
       [-4.52924236e-02],
       [ 1.56915449e-01],
       [ 3.43722904e-01],
       [-2.93437012e-02],
       [ 1.60299301e-01],
       [ 2.06633479e-01],
       [ 7.88492411e-02],
       [ 9.83437373e-03],
       [ 4.52408321e-02],
       [ 9.30441308e-02],
       [ 3.28240909e-01],
       [ 1.46104412e-01],
       [ 7.22300729e-02],
       [ 6.50983367e-02],
       [ 1.20308832e-01],
       [-2.05374879e-04],
       [ 1.14294052e-01],
       [ 3.11912545e-01],
       [ 2.69182588e-01],
       [ 4.87381174e-02],
       [ 7.66072066e-02],
       [-4.68132178e-03],
       [ 3.82160311e-02],
       [ 2.67858754e-01],
       [ 6.37868970e-03],
       [ 3.88511256e-01],
       [ 2.89491956e-02],
       [ 1.12863283e-01],
       [ 3.72847245e-01],
       [ 4.99852461e-02],
       [ 5.94357218e-02],
       [-6.33356347e-02],
       [ 5.45076675e-02],
       [ 5.01325478e-03],
       [ 8.45502085e-02],
       [ 6.82969244e-02],
       [ 4.78884993e-02],
       [-6.27362257e-03],
       [ 7.07609516e-02],
       [-9.78489409e-03],
       [ 2.80309947e-02],
       [ 2.02072705e-01],
       [ 2.87899899e-01],
       [ 4.17413603e-01],
       [-2.99410962e-02],
       [ 2.16229242e-01],
       [ 6.43788912e-02],
       [ 1.26797828e-01],
       [ 1.32866075e-01],
       [ 1.39668884e-01],
       [ 4.86614125e-02]])

In [52]:
new_data=[[0.508432,0.092678]]
pred_value=model.predict(new_data)
pred_value

C:\Users\Asus\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[-0.03662524]])